version: '3'

services:
  # web:
  #   build: .
  #   ports:
  #     - "80:8000"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   command: ["python", "app.py"]
  
  keycloak:
    depends_on:
      - postgres
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/kc
      KC_DB_DATABASE: kc
      KC_DB_USERNAME: kc
      KC_DB_PASSWORD: kc
      KC_HOSTNAME: localhost
    image: quay.io/keycloak/keycloak:23.0.3
    ports:
      - 18080:8080  
    restart: unless-stopped
    networks:
      - local-worst


  postgres:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: kc
      POSTGRES_USER: kc
      POSTGRES_DB: kc
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - local-worst

networks:
  local-worst: